[firebase]
type = "service_account"
project_id = "passegiatecavallo"
private_key_id = "15588fc9976980bcc75a99b93b44802ef3c3844f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC3egHVg9kNaXfn
H2SHKYrTfLBx5XlP3paqpsLCeBzEUXAaEUJZsVaplNZ0jJE8KsZU30PW9+/+RuNZ
ZVk6oE06HB2olYks3EAUPwxFSJcaBjhdOiFTCEDxP8V02hrFEjix+17NxiiFSCYB
2d5Ld4L6EXNgMdNyuNPo7AAcoU3ykm/lHN2vRYn9F71h4a+pov0WuK9o3DT+ARpw
/0aCcR/iiU9Wbw0GqdSuhaD5jknyCKoJm13+zd2Vd0lzYg8tBIbsy6tnJzEaI1y4
ehW05Quftxp3VExpOcGacIJ7lzZDDv6cOHlL5JnwYO4lEy6mjCWvtuW5g4XrEkdV
B2arqxrZAgMBAAECggEAAQtqqIGrShBiSIB1IPBffBgDBKj87XOb2b2gkP0gU81P
ZTSZMzvHXaiNZoU42/X14lyRjS8k8IaMi5EgRo1MV0L6979fNDBOVJctzZSt2I31
wvEeaLO8s+rsJ7/IpHvXswq2ddc1mpmoLr1D7tvPtPcFuEPcW3Q6L6KtVvxjnliM
3lxx9WDVZ87OxCmjmLGTypIBcpMSxlrRDBXrJFsP6yd/uw+9WBd81eSYDum7n/rT
vjTwZsg0HPOnXOgoySWl8MGtrD2kWQqJFj6iVxvRaqMx1VEq9aFVxG9zdB9gdGA+
wJvuHsN2se+fTSxY1mJzVv+GiiAqiEsFmzEE/mxTYQKBgQDi5HbXu5yzDiBHUQB0
ymLbm53JJA73bWoY6Azdk/DpHe1C33wsWusnfwi0dsFqx1+v+PC98phbzmWkvRbt
leGuS1szesYfgycJuiBnEG+mPMPBcvNQG93VlPzStBGoMSF7fYXkwLCTPe9/cXc6
MSt1Orv0IpEevZ4HN7bx9QOLOQKBgQDPA7E116wTTHj/OE9BrSHIA/MCAC17tLgB
hCrxRt4FZFryx8HM+bt3qoTu6FB9mEwHgalvnKVpqFrBDsjl3Hotg8UUEN6QTmzX
j6a5Xhxbje1HV5FAXUfAnJYnSAYlLll8BBJkCoCj4dLH8uKzjJfaFjg83u6FZNG2
65JdmNjsoQKBgE2BQ4NwKBgWJDqYVfKPS/O+lcim06H7szls0zBBoBLR0UF9vBoe
uKNWRq/2vR1vm6UuAXaxTxBVUe1TVmi0QVJblXzhXJpZH9W3yefK+oiryybi0HC2
BDI4YaDMOBffKJPZjgpVNDwn9Q7wwIyVTUYPWTMNN8trdHb8tjayvpIpAoGAQS8M
ccPDbyA5SUPV0PxPEsgLkKm1qKoy9mdDjk2eQ1xiNugnYf+QxBFxYjjMf3+hEQwG
6hoNC8PzL68UGyzdW8+OEs9tBUtsgkO9X8j+bOW3vSsZlYbJvSCRNzU6miKKEr7F
e7LC5teIo2UbdSXj+svcUW5w9JfWYR60K7yhMYECgYBeNSE8kYsDx7Pf8vW61uTn
YrY8aRJYgaPBIF5lDJncJhoqGnUmMb6zlBhx9NFRtAlLmTU9B2mkumdQ1IIvCfHc
g1Ch6AfMYA65/CDbTspEsRq076bQlu4AsnGAvMTWFaW3zcu0rkfchxYNeHrLzRTk
xZ49Pl0Rz8VEjmsR9wiOUA==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@passegiatecavallo.iam.gserviceaccount.com"
client_id = "118083089204431222213"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40passegiatecavallo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_service_account]
type = "service_account"
project_id = "passegiataproject"
private_key_id = "23d42bb69c4fd937dc9f12257cc4c6886dd5c37f"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoJr2yvrQblA/y\nh4Y4C9Nzjy7A7P67wjuXoWjf6p4n7hoaU7vN4B9ZymPvsf92dOV1fz/V7yEQd/Ju\nrlCMBZPsb3zoOoxmr5jK8HrMvFmIt46KeuGCw3s5OU3JaM58eMiSnfEFMggo2Tzk\nrIEOdowvrxTDXzzpKqu7Z0XvOELF5MFj9hCoWyWcjnzWQ5TrR3E5DW7p01xjGwQh\nNqnp4u09apruL751OaGleREdbyOGRlYQ8Q48Bv1kcFcuuCELINgZma7YTgGvnWI1\nWghxSjB42SXh0LiLCDk+2ReGgnq3hNNZIhYwvJrrtD5mO+mWDn63tXPpVx4QDxhM\nrqKEhgY1AgMBAAECggEAOwElLdTXdJn3Ip7FzWLw9yr2OAKxvIcCzEl6eKBmkRJv\nHG/nhe2wcpyfhtvKDfIlFp7pcpOv4YyFiKsoXooShzPz+7WX0OyrTAMoxDEPpfbr\nUNKf0XfxBHqEPjnFw03K7A/6JF2TGWppgMC7pKyaspzYR1pjEFrF2kP5+WCfpbr3\nIbGFMfU4lKgvgvb9D4RXa2m/aGW8BScQp+4VU6sxGJnDCL3XnJ+DJqrn8bFhjP+U\nEK9fToxVbzgI5KYsLLYJefX4tTESnvZtgGxwLZ63r5kGB04zuCJ3P07CYUpnkp3c\np9s6B/oDn//AIdaLvkiez7tknDQo9x4K7oJksjPvnQKBgQDXB1seSosJUEtYWWO6\n5LeWjK1juKQzNqAoh53iHTM2rHK91L+anBEcKgKUT906aRCQs2kS5AkzNnEqe9tw\npVw52W3T65uzLYWA+r08XGVr+S43uI3PSnREt2bFXlRuOFBA1/9aCGMFybVMz2LF\nX6Ml4toGDfCdy+/E/2NlC8xi2wKBgQDIMM4fC2YhBOjT4U/WkbHlbfIYl+KrQyHh\n/V/zBwXX2lnoAMVq4CuEtlEFm3NZ0fq0V34p4Do2vikeSVHmDfUVlaMPIZ60nATW\nz6hyEYtJO1fpsZGaKA1mWutABcYLjOo93FcttjP7xMX1R0rNfGbFTssmh0Slp6+V\nPbd+1NWgLwKBgDoy6XyXXG5W5y2wdAe/o9kBlmRpMzgRTuPpYNg0YwonPp8WmA12\ntELVNAGEZDJNAYjIpmXQhpTv5U1EXK5ucznNGabEHE4wwfOY6eMOdvz0Yof+UZOL\naVC3+v7sexmh8Ea8r4ZkwrhsUb/KWcdmDThR4ATHfRqYefrtzK8qtFUFAoGAIV5h\nPTN9NovG82pfEHkAmimVbRwEIF/0SeMeFzhYdP5kdhOK1KHBH0H0h2a9937UtzLO\nSNSjX3SbDf1StXImJA7pOyBzf89xzwyWG01pVi+aG84JYxTCBwmopOdRd6NpeB4+\nOdRhHdpS1OupQE84IjNcEXQCsUoeLlY3O+DmKukCgYEApZMXUGKtnzfztFhOGZ3q\nWXJtAf+Hx429M1T9bQpiglqKjhOzYA61l5nFCPbnn/0CzPJLJqbHI3om5iyloONF\nzMzcG0f8CqXypOKZVS3JQv6jZn1z+QPLu1ijMCIdozEIlDcOOmKnanEefbYy1RT0\nWM1O4Fa+ELaTv7Hb7ogm4TQ=\n-----END PRIVATE KEY-----\n"
client_email = "mypassegiataplanner@passegiataproject.iam.gserviceaccount.com"
client_id = "102069719398477339021"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mypassegiataplanner%40passegiataproject.iam.gserviceaccount.com"
universe_domain = "googleapis.com"