[firebase]
type = "service_account"
project_id = "passegiatecavallo"
private_key_id = "613a8cb7f41a8d2853b6c29fc340bbb95b831000"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDWZkkH5qGg3kG+
Qt9qdqjszStDmRD5CMb6QI10wDFCUJGQvHClYt0192Vi4s1xyAO+vDaNcOGwLU/7
+MrtZm2uEuNNzrTierdtwzbM1F2epoDSlqjrGeLmSiq4ynUFJ2UYRP2iM/0/SIgz
DGGUsAOnkYU3js91ljFnmmdpJiPlDIAs+5CdP3lGXTnJuZ85b9dmweY4vqX+Q/mO
/7G8mjWCCoXleUAFZTXYotCRZ+lbH0uOQw4r1H+QZWxCg+LOky105dJY/hwDGtC+
4EmzTju6P8PAIYIsZMlvPvl2tKxJGes8pMjnT5Tnl+HhKmtJQHQ+UzuspntWDvEZ
kd5wCUSbAgMBAAECggEAHG6WEsEoAABZcZTGsgSoZDbVHPLIiG38jSVQXQI7xhKP
K0WCHrycn1J+lH2FRyiCLqIhDeLBWy63I7AboR3rP6FrmV7nJ/2kI582vjUPcUGd
Zc/q+LqHF4kQX08h85wE0RIdHIyOcfz5auOicShiY69tni+HHY3cYWPdgNk4+1/N
4IkqGEQmZdoYvQVGLCdwCkppEP09uCUFU5FdLgdXfKZzRai7GitwD10LltLmm941
tUq+81dlgXeqTtzWfVoHnRh+5EagFKD2jH5hd2xpvOy5EvnB6dedVi5OWGqqSzj7
sNHsLLMAF9oszfaPPHg9MDYNFkQhZNkLNHgiHIPxyQKBgQDqTqq3hyNbWp0F2O1O
lM1AauLGNJKoJOu8uDyPTfor8p4YM7dfO25VDdLUeDwG+0I/NX+NcBowVayBmYRd
PXiIHTHO/n/uDtWHm5pA95VISjd5KcXUZPeTJATMYUoUy3Y0MQjkE9Itj7GcDOV4
PxNFWIgCfUT6HvhXx2enlSW/VQKBgQDqP8igQObe6jvmUjzFe0Lh3lBuTEU+Z5gd
AmU1H/4LgSs3OjnMrG8NAt0YDkIj3IaMlRNhNoxN2VYoeOSAHKZxpN/BWZCFGzW6
UqP4PmvUvBpgkfljYrOqPN0FgNdZ19q2I1UNi43B+6pmOfgm/7SpCZNWRyy64+Rv
J5djwYaULwKBgQC8mEtjZBv6eUownbYNbUp0klQsc76kJuu0wJrGQl6epy/HjUEJ
H14kifbsXEb825ssI5SitNvvkdZDjtzy6/qrnMwtr74rULdg6sdTibUYNdzG4u/A
kPCR+AkAtUKa0FY5lkpwwt+HGsU8NUky65pIVAVN86Tkqq78gJ2XTz7N7QKBgH2z
fJWCPmGgkEQoHTRb0KgkBEUr6Hx0Wsw2XNkFMe46glZAiIOshGsW/k3KWPOlgw4t
cRjZjLC5z+In/XZB6Y9SSkAXL9Y9o7c4YYT0+ihOSFlJ++m5LXBM+M3bNbSggFz8
2MdL++X8hpQUx3UmAmwzFz1VNEuVvx9mv3Zogy9BAoGADax/x0ZlnaOikl5a9fjl
nVtTsNEZh9PRPJTnDgHe3CYcp9w2TLAVEPqpZNF1U30XAHeBkxozM36w0frN0tan
Pl5e3fP4XLVTJGLBbdqqJXy/mcjPQclj8w4KIM+HWsklddviVE78s4hpBW7D6Xfl
ln5znfk0wgOoHUzEhHtYA6c=
-----END PRIVATE KEY-----"""

client_email = "firebase-adminsdk-fbsvc@passegiatecavallo.iam.gserviceaccount.com"
client_id = "118083089204431222213"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40passegiatecavallo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[gcp_service_account]
type = "service_account"
project_id = "passegiataproject"
private_key_id = "23d42bb69c4fd937dc9f12257cc4c6886dd5c37f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoJr2yvrQblA/y
h4Y4C9Nzjy7A7P67wjuXoWjf6p4n7hoaU7vN4B9ZymPvsf92dOV1fz/V7yEQd/Ju
rlCMBZPsb3zoOoxmr5jK8HrMvFmIt46KeuGCw3s5OU3JaM58eMiSnfEFMggo2Tzk
rIEOdowvrxTDXzzpKqu7Z0XvOELF5MFj9hCoWyWcjnzWQ5TrR3E5DW7p01xjGwQh
Nqnp4u09apruL751OaGleREdbyOGRlYQ8Q48Bv1kcFcuuCELINgZma7YTgGvnWI1
WghxSjB42SXh0LiLCDk+2ReGgnq3hNNZIhYwvJrrtD5mO+mWDn63tXPpVx4QDxhM
rqKEhgY1AgMBAAECggEAOwElLdTXdJn3Ip7FzWLw9yr2OAKxvIcCzEl6eKBmkRJv
HG/nhe2wcpyfhtvKDfIlFp7pcpOv4YyFiKsoXooShzPz+7WX0OyrTAMoxDEPpfbr
UNKf0XfxBHqEPjnFw03K7A/6JF2TGWppgMC7pKyaspzYR1pjEFrF2kP5+WCfpbr3
IbGFMfU4lKgvgvb9D4RXa2m/aGW8BScQp+4VU6sxGJnDCL3XnJ+DJqrn8bFhjP+U
EK9fToxVbzgI5KYsLLYJefX4tTESnvZtgGxwLZ63r5kGB04zuCJ3P07CYUpnkp3c
p9s6B/oDn//AIdaLvkiez7tknDQo9x4K7oJksjPvnQKBgQDXB1seSosJUEtYWWO6
5LeWjK1juKQzNqAoh53iHTM2rHK91L+anBEcKgKUT906aRCQs2kS5AkzNnEqe9tw
pVw52W3T65uzLYWA+r08XGVr+S43uI3PSnREt2bFXlRuOFBA1/9aCGMFybVMz2LF
X6Ml4toGDfCdy+/E/2NlC8xi2wKBgQDIMM4fC2YhBOjT4U/WkbHlbfIYl+KrQyHh
/V/zBwXX2lnoAMVq4CuEtlEFm3NZ0fq0V34p4Do2vikeSVHmDfUVlaMPIZ60nATW
z6hyEYtJO1fpsZGaKA1mWutABcYLjOo93FcttjP7xMX1R0rNfGbFTssmh0Slp6+V
Pbd+1NWgLwKBgDoy6XyXXG5W5y2wdAe/o9kBlmRpMzgRTuPpYNg0YwonPp8WmA12
tELVNAGEZDJNAYjIpmXQhpTv5U1EXK5ucznNGabEHE4wwfOY6eMOdvz0Yof+UZOL
aVC3+v7sexmh8Ea8r4ZkwrhsUb/KWcdmDThR4ATHfRqYefrtzK8qtFUFAoGAIV5h
PTN9NovG82pfEHkAmimVbRwEIF/0SeMeFzhYdP5kdhOK1KHBH0H0h2a9937UtzLO
SNSjX3SbDf1StXImJA7pOyBzf89xzwyWG01pVi+aG84JYxTCBwmopOdRd6NpeB4+
OdRhHdpS1OupQE84IjNcEXQCsUoeLlY3O+DmKukCgYEApZMXUGKtnzfztFhOGZ3q
WXJtAf+Hx429M1T9bQpiglqKjhOzYA61l5nFCPbnn/0CzPJLJqbHI3om5iyloONF
zMzcG0f8CqXypOKZVS3JQv6jZn1z+QPLu1ijMCIdozEIlDcOOmKnanEefbYy1RT0
WM1O4Fa+ELaTv7Hb7ogm4TQ=
-----END PRIVATE KEY-----"""
client_email = "mypassegiataplanner@passegiataproject.iam.gserviceaccount.com"
client_id = "102069719398477339021"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/mypassegiataplanner%40passegiataproject.iam.gserviceaccount.com"
universe_domain = "googleapis.com"